name: happy_tokens
description: "Rewards Made Simple"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version: 1.0.1+44 --android
#version: 43.0.1+44 --ios
version: 43.0.4+47


environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.3.10
  get: ^4.6.6
  http: null
  shared_preferences: ^2.2.1
  flutter_onboarding_slider: ^1.0.11
  loading_animation_widget: ^1.2.1
  pinput: ^5.0.0
  awesome_snackbar_content: ^0.1.4
  connection_notifier: ^2.0.1
  persistent_bottom_nav_bar_v2: ^5.3.1
  google_fonts: ^5.0.0
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  location_picker_flutter_map: ^2.1.0
  map_picker: ^0.0.3
  google_maps_flutter: ^2.2.8
  geocoding: ^3.0.0
  dotted_border: ^2.1.0
  file_picker: ^8.0.0+1
  uuid: ^4.5.1
  dio: ^5.7.0
  image_picker: ^1.0.8
  crypto: ^3.0.3
  razorpay_flutter: ^1.4.0
  super_tooltip: ^2.0.9
  flutter_dash: ^1.0.0
  intl: ^0.18.1
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.2.0
  fl_chart: ^0.69.0
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  permission_handler: ^11.3.1
  upgrader: ^10.3.0
  screenshot: ^2.5.0
  share_plus: ^7.2.2
  path_provider: ^2.1.4
  firebase_crashlytics: ^3.4.18
  firebase_analytics: ^10.8.9
  connectivity_plus: ^5.0.2
  sentry: ^8.14.1
  device_info_plus: ^9.1.2
  cached_network_image: ^3.3.1





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#282974"
  adaptive_icon_foreground: "assets/icons/fore_background_icon.png"
  image_path: "assets/icons/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/splash.png
  android_gravity: center


  android_12:
    image: assets/icons/splash.png
    color: "#FFFFFF"
    icon_background_color: null
    web: false

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/onboard/
    - assets/icons/dashboard/
    - assets/icons/account/
    - assets/icons/shop_details/
    - assets/icons/payment/
    - assets/icons/refer/
